package info.mhylle.playground.lpr3.model.SKS;

/**
 * Created by mnh on 25-01-2017.
 */
public enum SksCode
{
  BOOKING("AAF"),
  INDLAEGGELSE("AAF1"),
  GENINDLAEGGELSE("AAF11"),
  INDLAEGGELSE_BRUGER_SENG("AAF12"),
  UDSKRIVNING_BRUGER_SENG("AAF13"),
  AMBULANT("AAF2"),
  FORUNDERSOEGELSE("AAF20"),
  FOERSTEGANGSBESOEG("AAF21"),
  AMBULANTBESOEG("AAF22"),
  KONTROLBESOEG("AAF23"),
  OPERATION_NERVESYSTEM("KAB"),
  OPERATION_SPINALCORD("KABB"),
  OPERATION_EXCISION("KABB00"),
  OPERATION_RESEKTION("KABB10"),
  OPERATION_DRAINAGE("KABB20"),
  OPERATION_DESTRUCTION("KABB30"),
  OPERATION_REMOVAL("KABB40"),
  OPERATION_OTHER("KABB99"),
  EOG("UCGA"),
  ERG("UCGD"),
  EELEKTRORETINOGRAFI_DARK("UCGD00"),
  AKUT("ATA1"),
  AKUT_DAYTIME("ATA11"),
  AKUT_DAYTIME_CONSEQUENCE("ATA11A"),
  AKUT_DAYTIME_NO_CONSEQUENCE("ATA11B"),
  AKUT_NO_DAYTIME("ATA12"),
  URGENT("ATA2"),
  URGENT_DAYTIME_CONSEQUENCE("ATA21"),
  URGENT_DAYTIME__NO_CONSEQUENCE("ATA22"),
  ELEKTIV("ATA3"),
  SELFPAYED("AZAB1"),
  INSURANCEPAYED("AZAB2"),
  MUNICIPALITYPAYED("AZAB4"),
  MONTHLY("ATTM01"),
  MONTHLY2("ATTM02"),
  MONTHLY3("ATTM03"),
  MONTHLY4("ATTM04"),
  MONTHLY6("ATTM05"),
  MONTHLY12("ATTM12"),
  SPECIALIZATION_PLANNING("AZAC"),
  SPECIALIZATION_MAIN("AZAC2"),
  SPECIALIZATION_REGIONAL("AZAC3"),
  SPECIALIZATION_SPECIALIZED("AZAC4"),
  CAUSE_MEDICAL_ASSESSMENT_WITH_CONSULT("AVAA01"),
  CAUSE_MEDICAL_ASSESSMENT_WITHOUT_CONSULT("AVAA02"),
  REFERRAL_WITHOUT_TIME("AFF85"),
  LABEL_CANCER("ELBL001"),
  LABEL_KOL("ELBL002"),
  LABEL_DIABETES("ELBL003");

  private String code;

  SksCode(String code)
  {
    this.code = code;
  }

  public String getCode()
  {
    return code;
  }
}